--- #YAML:1.0
name:                optimize
version:             0.03_01
abstract:            ~
license:             ~
author:              
    - Arthur Bergman
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    B::Generate:                   1.34
    DynaLoader:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
