--- #YAML:1.0
name:               optimize
version:            0.03_02
abstract:           ~
author:
    - Arthur Bergman
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Attribute::Handlers:  0
    B::Generate:          1.34
    B::Utils:             0
    DynaLoader:           0
    Hook::Scope:          0.02
    optimizer:            0.02
resources:
    license:     http://dev.perl.org/licenses/
    repository:  http://github.com/rurban/optimize
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
