---
abstract: unknown
author:
  - 'Artur Bergman'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.58, CPAN::Meta::Converter version 2.110930001'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: optimize
no_index:
  directory:
    - t
    - inc
requires:
  Attribute::Handlers: 0
  B::Generate: 1.34
  B::Hooks::EndOfScope: 0.09
  B::Utils: 0
  DynaLoader: 0
  optimizer: 0.06
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/rurban/optimize
version: 0.03_03
